### ISSUE TITLE
Maintenance Version larger than int16

### ISSUE THREAD

**Issue by oholloway** [IxMilia/Dxf#88]
While translating a file exported using Bentley Micro Station using IxMilia Dxf it was observed that the Maintenance Version was greater than an int16.

This can be resolved by changing it from short to int on lines 303 and 3709 in the DxfHeaderGenerated.cs file. I have submitted a pull request with this change. 

Cheers

**Comment by brettfo** [comment]
According to the [spec](http://help.autodesk.com/view/OARX/2019/ENU/?guid=GUID-2553CF98-44F6-4828-82DD-FE3BC7448113) all code 70 values have to be an int16, so I'm really reluctant to change this because it would enable much too large values to be written which could break compat with AutoCAD. What's the actual value that MicroStation writes?

**Comment by ssippe** [comment]
@brettfo We are getting a similar issue where the dxf was generated as Save As from Autocad P 46.0.0 v2019. So despite the spec it looks like Autocad is simlarly writing ints > int16 to the field. We can send you the dxf if you want.

Unable to cast object of type 'System.Int32' to type 'System.Int16'.

   at IxMilia.Dxf.DxfHeader.SetHeaderVariable(String keyName, DxfCodePair pair) in D:\IxMilia\Dxf\src\IxMilia.Dxf\Sections\Generated\DxfHeaderGenerated.cs:line 3709
   at IxMilia.Dxf.Sections.DxfHeaderSection.HeaderSectionFromBuffer(DxfCodePairBufferReader buffer) in D:\IxMilia\Dxf\src\IxMilia.Dxf\Sections\DxfHeaderSection.cs:line 437
   at IxMilia.Dxf.Sections.DxfSection.FromBuffer(DxfCodePairBufferReader buffer, DxfAcadVersion version) in D:\IxMilia\Dxf\src\IxMilia.Dxf\Sections\DxfSection.cs:line 71
   at IxMilia.Dxf.DxfFile.LoadFromReader(IDxfCodePairReader reader) in D:\IxMilia\Dxf\src\IxMilia.Dxf\DxfFile.cs:line 257
   at IxMilia.Dxf.DxfFile.Load(Stream stream) in D:\IxMilia\Dxf\src\IxMilia.Dxf\DxfFile.cs:line 196
   at plansTest1.UnitTest1.ReadDxf() in c:\code\personal\plansTest1\UnitTest1.cs:line 37

**Comment by brettfo** [comment]
@ssipe This sounds like it could be similar to #92 where the maintenance version was a code 90 int instead of the expected code 70 short.  If you could send me a drawing that would be ideal.  If you don't want to post it here you can email it directly to me at `brett.forsgren@outlook.com`.
